export const about = {
  title: 'About',
  anchors: [
    ['rating', 'How the rating works'],
    ['judge', 'What the judge sees'],
    ['writes', 'How writes work'],
    ['ladders', 'The ladders'],
    ['limits', 'Limits'],
    ['privacy', 'Privacy'],
    ['status', 'Status'],
    ['contact', 'Contact'],
  ] as const,
  rating: {
    p1: 'Every entry carries a Glicko rating: a number and a deviation, shown as ± next to it. The deviation is how settled the number is; it narrows as matches are played and widens slowly when an entry sits idle.',
    p2: 'A new entry starts from the rubric: the analysis scores it, the score seeds a rating between 800 and 1600, and eight placement matches in the general ladder (then six in each domain ladder it qualifies for) move it from there. Each match is judged in both orderings; when the judge disagrees with itself the match is a draw.',
    p3: 'The ladder moves under you: as new resumes are placed, yours is re-matched against them, which is why a rating can drift a few points a week.',
    tiersHeading: 'Tiers',
    provisional: 'Provisional',
  },
  judge: {
    p1: 'The judge never sees the text. It sees a card: institutions, employers, titles, year ranges, numbers, awards, publications by venue. What never reaches it: a name, contact details, links, exact dates.',
    p2: 'Five sub-scores (pedigree, trajectory, impact, selectivity, breadth) are weighted differently per ladder, and the stage-relative score carries most of the headline number. The weights are on every result page.',
    p3: 'Scoring uses a larger model; matches use a faster one; a small model checks that the text is a resume at all. The judge gives a reason every time, and the reason is shown.',
    p4: 'Judge notes and cards quote employer and school names by design.',
  },
  writes: {
    p1: 'This site has no server. Submitting calls GitHub directly and starts a workflow in the public repository; the workflow reads the text, calls the model, and commits the result to a branch, which is then published as the files this site reads. The key that lets the page start that workflow is public and can do nothing except start or cancel our workflows; the workflow checks everything it is given. If that key is withdrawn, a GitHub issue form does the same job. Nothing you submit passes through anything but your browser, GitHub, and Anthropic.',
  },
  ladders: {
    p1: 'Four ladders: general, finance, tech, academia. Every entry is on the general ladder. A domain ladder includes it when the analysis finds the resume relevant to that field (relevance of 0.35 or more). The ladder hint you choose is shown first; it does not change the rating.',
    p2: 'Each ladder can be filtered by career stage, which the analysis infers from the text. Ranks within a stage are counted within that stage.',
  },
  limits: {
    p1: '20 entries an hour across the whole site, a daily analysis budget, 15,000 characters of text, English only, no file is ever uploaded.',
    p2: 'When the hourly cap is hit the workflow writes nothing and the entry is dropped; the upload page warns before you send. When the daily budget is spent, new entries are stored and analysed after 00:00 UTC, in order; up to twenty submissions that arrived at the same moment may each still be analysed, so the budget can overshoot by about $4.',
    p3: 'One entry per handle at a time. Resubmitting replaces the text; the rating carries over as the starting estimate.',
  },
  privacy: {
    p1: 'Public: the redacted text, the analysis, the card, the matches and ratings, and the handle when you choose to show it. Never on our side: the file, an email address, a name, an IP log beyond what GitHub keeps.',
    p2: 'The data lives in a public git branch. Deleting removes the entry from the site within minutes and from the repository’s history within 7 days; copies made by others are outside our control.',
    p3: 'Judge notes and cards quote employer and school names by design. Text sent to the model is handled under Anthropic’s API terms.',
    p4: 'Something personal slipped through? Delete the entry with your key, or send the id to the contact address.',
  },
  status: {
    heading: 'Status',
    asOf: (t: string, ago: string) => `as of ${t} · ${ago}`,
    rows: {
      awaitingAnalysis: 'Awaiting analysis',
      awaitingPlacement: 'Awaiting placement',
      spend: 'Spend today',
      lastRerank: 'Last rerank',
      lastDeploy: 'Last deploy',
      /** The distinct count (general-ladder board), not status.counts.rated, which sums the four ladders. */
      rated: 'Resumes rated',
      matches: 'Matches played',
      channel: 'Direct channel',
      schedule: 'Schedules',
      token: 'Token expires',
      alerts: 'Alerts',
      paused: 'Submissions',
    },
    channel: { open: 'open', down: 'down, fallback only', limited: 'rate limited', checking: 'checking' },
    schedule: { on: 'enabled', off: 'disabled' },
    none: 'none',
    paused: 'paused',
    open: 'open',
    overBudget: 'placement resumes 00:00 UTC',
    wry: 'All of this is a git branch.',
    error: 'Could not load. GitHub Pages did not answer. Retrying.',
  },
  contact: {
    p1: 'Questions, takedowns, and anything personal that slipped through:',
    noEmail: 'this deployment has no contact mailbox configured; use the repository’s issue tracker',
    issues: 'the issue tracker',
    repo: 'The repository',
  },
} as const;
