export const arena = {
  title: 'Arena',
  question: 'Which did the judge prefer?',
  a: 'A',
  b: 'B',
  tooClose: 'Too close to call',
  skip: 'Skip',
  next: 'Next',
  preferred: (side: 'A' | 'B') => `The judge preferred ${side}.`,
  draw: 'The judge could not separate them: it picked differently in the two orderings, which counts as a draw.',
  agree: 'You agree with the judge.',
  disagree: 'You and the judge disagree.',
  drawGuess: 'You called it close; so did the judge.',
  streak: (n: number) => `streak ${n}`,
  guesses: (n: string) => `${n} guesses`,
  agreement: (pct: string) => `${pct} agree`,
  explainer: 'These are real matches the judge already decided. Your guesses stay in this browser and change nothing; the judge’s reason is the lesson.',
  wryTen: 'Ten in a row. You may be the judge.',
  wryFive: 'Five disagreements. One of you is wrong, and the judge is not sure it is you.',
  empty: { title: 'Not enough matches to guess from yet.', body: 'The arena opens once a ladder has twenty judged matches.' },
  exhausted: { title: 'You have seen every recent match on this ladder.', body: 'New ones arrive with each rerank.' },
  anotherLadder: 'Try another ladder',
  category: 'Ladder',
  teaser: { heading: 'Arena', body: 'Two resumes, anonymised. Guess which the judge preferred. Then read why.', action: 'Try it' },
  card: {
    judgeTag: 'judge’s pick',
    years: (y: number) => (y === 1 ? '1 year' : `${y % 1 === 0 ? y : y.toFixed(1)} years`),
    education: 'Education',
    experience: 'Experience',
    projects: 'Projects',
    publications: 'Publications',
    awards: 'Awards',
    leadership: 'Leadership',
    notable: 'Notable',
    skills: 'Skills',
    key: 'key',
  },
} as const;
