export const me = {
  title: 'Manage your entry',
  entryLabel: 'Entry',
  keyInput: {
    label: 'Or paste a key',
    placeholder: 'rak-…',
    helper: 'Pasting a key from another device manages that entry here and remembers the key in this browser.',
    handleLabel: 'Handle',
    use: 'Use this key',
    checking: 'Checking.',
  },
  errors: {
    wrongKey: { title: 'That key does not match.', body: 'Keys are 52 characters after rak-, in groups of four. Check for a missing group; keys are case-insensitive.' },
    notAKey: { title: 'That is not an owner key.', body: 'Keys start with rak- and have 13 groups of four characters.' },
    noEntry: { title: 'No entry under that handle.', body: 'It may have been deleted, or the handle was never registered.' },
    channelDown: { title: 'The direct channel is down.', body: 'Changing visibility and resubmitting need it. Try again later; deletion still works through the fallback.' },
  },
  empty: { title: 'No key on this device.', body: 'Paste the key you saved when you submitted, or submit a resume.' },
  lost: 'Without the key the entry cannot be changed or deleted. It will keep being rated. You can submit again under a new handle.',
  summary: { analysed: 'analysed, awaiting placement', pending: 'pending', result: 'Full result', submitted: (d: string) => `submitted ${d}`, versions: (n: number) => `${n} ${n === 1 ? 'version' : 'versions'}` },
  pendingEntry: {
    line: (time: string) => `Submitted ${time}. Still being analysed; manage actions appear once it is.`,
    link: 'Follow it on the result page',
  },
  visibility: {
    label: 'Show my handle on the ladders',
    sending: 'Sending.',
    received: 'Received. Changes land with the next deploy, a few minutes.',
    notApplied: 'Not applied yet. Check back, or try again.',
    toastShown: (h: string) => `Now showing as ${h}`,
    toastAnon: 'Now anonymous',
  },
  resubmit: { line: 'Replace the text with a new version. The rating carries over as the starting estimate; the old text is removed.', button: 'Resubmit a resume' },
  del: {
    line: 'Delete this entry.',
    wry: 'This is the only button on the site with a second step.',
    button: 'Delete this entry',
    dialogTitle: 'Delete this entry?',
    dialogBody:
      'This removes the text, the analysis, and the rating from the ladders with the next deploy. Opponents keep their results; your side of each match becomes an anonymous placeholder. The handle stays reserved for your key; nobody else can take it. This cannot be undone.',
    confirmLabel: 'Type the handle to confirm',
    received: 'Deletion received. It lands with the next deploy, a few minutes. The link will then say the entry was deleted.',
    receivedLink: 'The entry’s page',
    fallbackBody:
      'The fallback is a GitHub issue form with the id and handle prefilled; it needs a GitHub account. Paste your key into the field called owner_key. The key becomes public, which is acceptable only because deletion makes it useless; that is why only deletion has a fallback.',
    fallbackButton: 'Copy key and open the form',
    fallbackOpened: 'Opened. Once you submit the issue, the deletion lands with the next deploy.',
  },
  device: {
    heading: 'This device',
    forget: 'Forget this key on this device',
    forgotten: 'Forgotten. The entry is unchanged; paste the key to manage it again.',
    show: 'Show key',
    hide: 'Hide key',
    copy: 'Copy key',
    copied: 'Copied',
  },
  manageDisabled: 'Manage actions are switched off in this build.',
} as const;
