// Upload page copy (product-ux.md §10.1 with the §11.6 deltas). Keys follow §10.
export const upload = {
  title: 'Upload a resume',
  lead: 'A PDF, a Word file, or pasted text. Everything up to the submit button happens in this browser.',
  rail: ['File', 'Preview', 'Details', 'Submit'] as const,
  leaveGuard: 'The text you prepared will be lost if you leave. Leave anyway?',

  dropzone: {
    idle: 'Drop a PDF or DOCX here, or choose a file.',
    constraints: 'PDF or DOCX · up to 10 MB · 1–3 pages works best',
    dragover: 'Release to read it.',
    mobile: 'Choose a file',
    reading: (filename: string) => `Reading ${filename}.`,
    readingSecondary: 'Extracting text and layout. Nothing is uploaded.',
    chooseAnother: 'Choose another',
  },
  paste: {
    switch: 'Paste text instead',
    label: 'Resume text',
    placeholder: 'Paste the resume text here.',
    helper: 'Pasted text has no layout, so layout metrics will be blank.',
    use: 'Use this text',
    switchBack: 'Choose a file instead',
  },
  fileError: {
    type: { title: 'That is not a PDF or DOCX.', body: 'Export it as a PDF, or paste the text.' },
    size: { title: 'The file is over 10 MB.', body: 'Resume files are usually under 500 KB. Re-export without embedded images, or paste the text.' },
    noText: {
      title: 'No readable text in this file.',
      body: 'It is probably a scan. Export from the original document, or paste the text; scanned resumes also fail most applicant-tracking systems.',
    },
    unreadable: { title: 'Could not read the file.', body: 'It may be encrypted or damaged. Re-export it, or paste the text.' },
  },

  preview: {
    heading: 'Check what will be public',
    lead: 'We removed what looked like contact details. Read it once; fix anything the extraction got wrong.',
    textareaLabel: 'Text to be submitted',
    counter: (chars: string) => `${chars} / 15,000`,
    over: (n: string) => `Over the limit by ${n} characters. Trim it here.`,
    under: 'Fewer than 400 characters. Paste or upload more.',
    redactSelection: 'Redact selection',
    redactSelectionTitle: 'Replaces the selected text with [redacted]',
    poor: { title: 'The extraction looks poor.', body: 'Columns or tables came out in the wrong order. Fix the order here, or paste the text from the original document.' },
    metricsHelper: 'Layout metrics go to the analysis as numbers; the file does not.',
    publicNotice:
      'Exactly this text becomes public, attached to your handle or an anonymous id, in a public GitHub repository anyone can read. The original file never leaves this browser.',
    wry: 'Recruiters read this part too. Now you know how it feels.',
    use: 'Use this text',
    useDisabledOver: 'Trim the text to 15,000 characters first',
    useDisabledUnder: 'Add at least 400 characters first',
    chooseAnother: 'Choose another file',
    back: 'Back',
  },
  removed: {
    heading: 'Removed',
    headingCount: (n: number) => `Removed (${n})`,
    kind: {
      name: 'Name, from the first line',
      email: ['Email', 'Emails'],
      phone: ['Phone', 'Phones'],
      url: ['Link', 'Links'],
      address: ['Address', 'Addresses'],
      manual: ['Redacted by you', 'Redacted by you'],
    },
    notAName: 'Not a name',
    empty: 'Nothing matched. Check the text for a name, email, or phone.',
    footnote: 'Removal is by pattern and can miss things. The text is yours to edit.',
  },

  details: {
    heading: 'Handle and ladder',
    handleLabel: 'Handle',
    handlePlaceholder: 'e.g. priya-n',
    handleHelper: '3 to 20 characters: lowercase letters, numbers, hyphens. It is how the entry appears when you choose not to be anonymous, and how you find it again.',
    handle: {
      checking: 'Checking.',
      available: 'Available.',
      taken: 'That handle is taken.',
      reserved: 'That handle is reserved.',
      blocked: 'That handle is not available.',
      invalid: 'Handles are lowercase letters, numbers, and hyphens, 3 to 20 characters, no hyphen at the ends.',
      yours: 'You hold the key for this handle. Submitting replaces your current entry; its rating carries over as the starting estimate.',
      unreachable: 'Could not check availability. The workflow checks again on arrival.',
    },
    ladderLegend: 'Which ladder is this mainly for?',
    ladderHelper: 'It is rated on every ladder it qualifies for. This one is shown first.',
    visibilityLabel: 'Show my handle on the ladders',
    visibilityHelper: 'Off means you appear as an anonymous id, like anon-k7q2m3x. The text and card are public either way; people who know you may recognise them.',
    consent: 'By continuing you confirm this is your own resume. The text is analysed by Claude, a model from Anthropic, through its API, and is public as shown in the previous step.',
    continue: 'Continue',
    continueDisabled: 'Choose an available handle',
    back: 'Back',
  },

  key: {
    heading: 'Your owner key',
    lead: 'This key is the only way to change or delete your entry. It is made in this browser and shown once. We store only its fingerprint.',
    copy: 'Copy key',
    copied: 'Copied',
    save: 'Save as file',
    fileContents: (handle: string, key: string) =>
      `ResumeArena owner key for ${handle}\n${key}\nKeep this. It is the only way to change or delete your entry at https://noahfinkelstein.github.io/resumearena/me\n`,
    savedCheckbox: 'I have saved the key somewhere I will find it.',
    storageNote: "It also stays in this browser's storage, which clears if you clear site data or switch devices.",
  },
  resubmit: {
    heading: (handle: string) => `Resubmitting as ${handle}`,
    lead: (handle: string) => `Your key for ${handle} is in this browser. Submitting replaces the current entry; the rating carries over as the starting estimate and the old text is removed.`,
  },
  summary: (handle: string, ladder: string, visibility: 'anonymous' | 'handle', chars: string) =>
    `${handle} · ${ladder} · ${visibility === 'handle' ? 'handle shown' : 'anonymous'} · ${chars} characters`,
  submit: {
    button: 'Submit for rating',
    disabled: 'Confirm you saved the key first',
    sending: 'Sending.',
    retrying: (n: number) => `Lost the connection. Retrying (${n} of 4).`,
    busy: (n: number) => `The arena is busy. Entries sent in the next ${n === 1 ? 'minute' : `${n} minutes`} may be dropped.`,
    paused: (msg: string) => msg || 'Submissions are paused. The about page says why.',
    exhausted: 'Today’s analysis budget is spent. New entries queue for tomorrow; resubmissions wait until then.',
  },
  submitError: {
    channel: {
      title: 'The direct channel is down.',
      body: 'The token that lets this page start the workflow is missing or revoked. The fallback is a GitHub issue form carrying the same fields; it needs a GitHub account, which the direct channel does not. The text is copied to your clipboard; paste it into the field called Resume text.',
    },
    rateLimited: { title: 'GitHub is rate limiting submissions.', body: 'Wait a minute and try again. Nothing was sent.' },
    refused: { title: 'GitHub refused the request.', body: 'Try again in a minute. If it keeps failing, use the fallback below.' },
    network: { title: 'Lost the connection.', body: 'Nothing was sent. Try again when you are back online.' },
  },
  fallback: {
    open: 'Copy text and open the form',
    retry: 'Try the direct channel again',
    note: 'Needs a GitHub account. The form has the same fields; the workflow treats both the same.',
    opened: 'Opened. Once you submit the issue, this page checks for the result.',
    resubmitUnsupported: 'Resubmission has no fallback: it would post your key publicly. Try the direct channel later.',
  },
} as const;
